#-------------------------------
# General Site Settings

menu:
- {name: 'Art', url: ''}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio of Isabel Goico'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

google-analytics-ua: 'UA-115309301-1'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # About

  Jeepers creepers

contact: >
  # Contact

  Hit me up

#-------------------------------
# Work Section

projects:
- {name: 'Prints for Progress', folder: 'pfp', file: 'projects/pfp.html'}
- {name: 'The Return of Mr. Koi', folder: 'koi', file: 'projects/koi.html'}
- {name: 'Brick + Mortar', folder: 'brmr', file: 'projects/brmr.html'}

#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/doodleswithizzy/'}
# - {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
