#-------------------------------
# General Site Settings

menu:
- {name: 'Art', url: ''}
- {name: 'About', url: 'pages/about.html'}
- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Portfolio of Isabel Goico'

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'thathungrymind'

#-------------------------------
# About Section

about: >
  # About

  Aspiring graphic designer, with a passion for cute dogs 

contact: >
  # Contact

  email izzy@izzy.graphics for info about commissions!

#-------------------------------
# Where all of the art links go

projects:
- {name: 'Prints for Progress', folder: 'pfp', file: 'projects/pfp.html'}
- {name: 'The Return of Mr. Koi', folder: 'koi', file: 'projects/koi.html'}
- {name: 'Glass Charcoal Drawing', folder: 'glass', file: 'projects/glass.html'}
- {name: 'Digital Watercolor landscape', folder: 'digital', file:'projects/digital.html'}
#-------------------------------
# Contact Section

social:
- {icon: 'instagram', link: 'https://www.instagram.com/doodleswithizzy/'}
# - {icon: 'envelope', link: 'mailto:#'}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'
